# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

name: check source

on:
  push:
    paths:
      - app/**

jobs:
  check-source:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
      
      - name: Get yarn cache
        id: yarn-cache
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: check source
        working-directory: ./app
        run: |
          yarn install --immutable
          yarn lint
          yarn check
